# Site settings
author: Annia Forney 
title: FlatIron Student Blog
header-img: img/home-bg.png
email: anniaforney@gmail.com
copyright_name: Annia Forney 
description: > # this means to ignore newlines until "baseurl:"
  Project Blog Posts 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AnniaForney

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
